//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostAccounting
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] public partial class CostMngTotal
    {
        public int year { get; set; }
        public int category { get; set; }
        public int month { get; set; }
        public decimal manufacturing_personnel { get; set; }
        public decimal manufacturing_depreciation { get; set; }
        public decimal manufacturing_rent { get; set; }
        public decimal manufacturing_repair { get; set; }
        public decimal manufacturing_stock { get; set; }
        public decimal manufacturing_other { get; set; }
        public decimal selling_personnel { get; set; }
        public decimal selling_depreciation { get; set; }
        public decimal selling_other { get; set; }
        public decimal operating_expenses { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_date { get; set; }
        public string del_flg { get; set; }
    }
}
