//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Divergence
    {
        public int year { get; set; }
        public int month { get; set; }
        public decimal materialCost { get; set; }
        public decimal laborCost { get; set; }
        public decimal contractorsCost { get; set; }
        public decimal materialsFare { get; set; }
        public decimal packingCost { get; set; }
        public decimal utilitiesCost { get; set; }
        public decimal otherCost { get; set; }
        public decimal packingFare { get; set; }
        public decimal materialCost_costing { get; set; }
        public decimal laborCost_costing { get; set; }
        public decimal contractorsCost_costing { get; set; }
        public decimal materialsFare_costing { get; set; }
        public decimal packingCost_costing { get; set; }
        public decimal utilitiesCost_costing { get; set; }
        public decimal otherCost_costing { get; set; }
        public decimal packingFare_costing { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_date { get; set; }
        public string del_flg { get; set; }
    }
}
