//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostAccounting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CostAccountingEntities : DbContext
    {
        public CostAccountingEntities()
            : base("name=CostAccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostMngTotal> CostMngTotal { get; set; }
        public virtual DbSet<DbSize> DbSize { get; set; }
        public virtual DbSet<Divergence> Divergence { get; set; }
        public virtual DbSet<Fare> Fare { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Machine> Machine { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Other> Other { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductBlend> ProductBlend { get; set; }
        public virtual DbSet<ProductCode> ProductCode { get; set; }
        public virtual DbSet<ProductContractor> ProductContractor { get; set; }
        public virtual DbSet<ProductMachine> ProductMachine { get; set; }
        public virtual DbSet<ProductMaterial> ProductMaterial { get; set; }
        public virtual DbSet<ProductMaterialsFare> ProductMaterialsFare { get; set; }
        public virtual DbSet<ProductPacking> ProductPacking { get; set; }
        public virtual DbSet<ProductPackingFare> ProductPackingFare { get; set; }
        public virtual DbSet<RowMaterial> RowMaterial { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<ProductSupplier> ProductSupplier { get; set; }
    }
}
