//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostAccounting
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] public partial class Other
    {
        public int year { get; set; }
        public int category { get; set; }
        public decimal wage_m { get; set; }
        public decimal wage_f { get; set; }
        public decimal wage_indirect { get; set; }
        public decimal utilities_fd { get; set; }
        public decimal utilities_ad { get; set; }
        public decimal allocation_fd { get; set; }
        public decimal allocation_ad { get; set; }
        public decimal allocation_labor { get; set; }
        public decimal allocation_sale { get; set; }
        public decimal allocation_mng { get; set; }
        public decimal allocation_ext { get; set; }
        public decimal rate_expend { get; set; }
        public decimal rate_loss { get; set; }
        public decimal tray_num { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_date { get; set; }
        public string del_flg { get; set; }
    }
}
