//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostAccounting
{
    using System;
    using System.Collections.Generic;
    
    [Serializable] public partial class ProductSupplier
    {
        public int year { get; set; }
        public string product_code { get; set; }
        public string supplier_code { get; set; }
        public int category { get; set; }
        public int type { get; set; }
        public decimal unit_price { get; set; }
        public decimal month_01 { get; set; }
        public decimal month_02 { get; set; }
        public decimal month_03 { get; set; }
        public decimal month_04 { get; set; }
        public decimal month_05 { get; set; }
        public decimal month_06 { get; set; }
        public decimal month_07 { get; set; }
        public decimal month_08 { get; set; }
        public decimal month_09 { get; set; }
        public decimal month_10 { get; set; }
        public decimal month_11 { get; set; }
        public decimal month_12 { get; set; }
        public string update_user { get; set; }
        public System.DateTime update_date { get; set; }
        public string del_flg { get; set; }
        public decimal num01 { get; set; }
        public decimal num02 { get; set; }
        public decimal num03 { get; set; }
        public decimal num04 { get; set; }
        public decimal num05 { get; set; }
        public decimal num06 { get; set; }
        public decimal num07 { get; set; }
        public decimal num08 { get; set; }
        public decimal num09 { get; set; }
        public decimal num10 { get; set; }
        public decimal num11 { get; set; }
        public decimal num12 { get; set; }
    }
}
