//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostAccounting.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CostAccounting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   31 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string bkfileStoragePeriod {
            get {
                return ResourceManager.GetString("bkfileStoragePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F0001#ｷｭｰｿｰ流通ｼｽﾃﾑ管内冷凍便,F0002#佐川急便関西,F0003#佐川急便関東,F0004#佐川急便九州,F0005#佐川急便四国,F0006#佐川急便信越,F0007#佐川急便中国,F0008#佐川急便東海,F0009#佐川急便道内,F0010#佐川急便東北,F0011#佐川急便北陸,F0012#燦～大島食品さけぱっぱ直送費,F0013#燦～丸美屋食品（MA3）,F0014#燦～浦幌ﾌﾘｰｽﾞﾄﾞﾗｲ(七草),F0015#ﾔﾏﾄ運輸沖縄,F0016#ﾔﾏﾄ運輸関西・中国,F0017#ﾔﾏﾄ運輸関東・信越,F0018#ﾔﾏﾄ運輸九州,F0019#ﾔﾏﾄ運輸四国,F0020#ﾔﾏﾄ運輸道内,F0021#ﾔﾏﾄ運輸東北,F0022#ﾔﾏﾄ運輸北陸・中部,F0023#ﾔﾏﾄ運輸冷蔵・冷凍便加算料金10～15kg,F0024#ﾔﾏﾄ運輸冷蔵・冷凍便加算料金5～10kg,F0025#ﾔﾏﾄ運輸冷蔵・冷凍便加算料金5kg以下,F0026#ライオン菓子～浦幌FD（パレット返却配送費） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string defaultFareData {
            get {
                return ResourceManager.GetString("defaultFareData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   001#鮭製品,002#野沢菜製品,003#コーン製品,004#七草,005#いちご製品,006#柚子製品,099#受託加工品,800#転売品,999#その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string defaultItemData {
            get {
                return ResourceManager.GetString("defaultItemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A#真空凍結乾燥機,B#熱風乾燥機,C#金属検出機・風力選別機,D#ホッパー・金属検出機（選別）,E#野菜洗浄機,G#スライサー,H#ブランチャー,I#ライスボイラー,J#遠心分離機,K#レオニーダー,L#３連蒸し器,M#シフター,N#粉砕機,O#リボンミキサー,P#金属検出機５００（乾燥）,Q#高速裁断機・連続皮むき機,R#ｽﾘｯﾄｽﾗｰｻｰﾕﾆｯﾄYS-9000W型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string defaultMachineData {
            get {
                return ResourceManager.GetString("defaultMachineData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   blend.xltx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string template_blend {
            get {
                return ResourceManager.GetString("template_blend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   compare.xltx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string template_compare {
            get {
                return ResourceManager.GetString("template_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   divergence.xltx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string template_divergence {
            get {
                return ResourceManager.GetString("template_divergence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   list.xltx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string template_list {
            get {
                return ResourceManager.GetString("template_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   product.xltx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string template_product {
            get {
                return ResourceManager.GetString("template_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rate.xltx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string template_rate {
            get {
                return ResourceManager.GetString("template_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   total_item.xltx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string template_total_item {
            get {
                return ResourceManager.GetString("template_total_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   total_supplier.xltx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string template_total_supplier {
            get {
                return ResourceManager.GetString("template_total_supplier", resourceCulture);
            }
        }
    }
}
